"""empty message

Revision ID: 1f72fe63169b
Revises: 4b84a8ad8261
Create Date: 2022-02-17 06:23:58.800240

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1f72fe63169b'
down_revision = '4b84a8ad8261'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_link_trackers_chat_id', table_name='link_trackers')
    op.drop_column('link_trackers', 'chat_id')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('link_trackers', sa.Column('chat_id', sa.BIGINT(), autoincrement=False, nullable=True))
    op.create_index('ix_link_trackers_chat_id', 'link_trackers', ['chat_id'], unique=False)
    # ### end Alembic commands ###
