"""empty message

Revision ID: 34c796e12d68
Revises: 9e00cc5487af
Create Date: 2022-02-17 08:43:01.407130

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '34c796e12d68'
down_revision = '9e00cc5487af'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
