"""empty message

Revision ID: 45de2cfdbd39
Revises: 72e0f25b5b71
Create Date: 2022-02-17 11:32:56.515743

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '45de2cfdbd39'
down_revision = '72e0f25b5b71'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
