"""empty message

Revision ID: 72e0f25b5b71
Revises: 9083dbc77804
Create Date: 2022-02-17 10:09:09.699817

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '72e0f25b5b71'
down_revision = '9083dbc77804'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
