"""empty message

Revision ID: 9db8cfbc3595
Revises: 0721605429b6
Create Date: 2022-02-17 08:49:17.602368

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9db8cfbc3595'
down_revision = '0721605429b6'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
