"""empty message

Revision ID: 9e00cc5487af
Revises: ec60c16be02d
Create Date: 2022-02-17 08:42:00.270792

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9e00cc5487af'
down_revision = 'ec60c16be02d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
