"""empty message

Revision ID: def6b96dcf6b
Revises: 29d2993aacb9
Create Date: 2022-02-17 08:26:10.015633

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'def6b96dcf6b'
down_revision = '29d2993aacb9'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
