"""empty message

Revision ID: ec60c16be02d
Revises: de8990d649e1
Create Date: 2022-02-17 08:40:44.267483

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ec60c16be02d'
down_revision = 'de8990d649e1'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
