"""empty message

Revision ID: 0721605429b6
Revises: 34c796e12d68
Create Date: 2022-02-17 08:45:00.454634

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0721605429b6'
down_revision = '34c796e12d68'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('chat_rooms', sa.Column('logo_url', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('chat_rooms', 'logo_url')
    # ### end Alembic commands ###
