"""empty message

Revision ID: 0fe72e384366
Revises: 45de2cfdbd39
Create Date: 2022-02-18 15:12:39.329663

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0fe72e384366'
down_revision = '45de2cfdbd39'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
