"""empty message

Revision ID: 162fffcec05b
Revises: 1f72fe63169b
Create Date: 2022-02-17 06:25:32.891039

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '162fffcec05b'
down_revision = '1f72fe63169b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
