"""empty message

Revision ID: 29d2993aacb9
Revises: 162fffcec05b
Create Date: 2022-02-17 08:24:59.168086

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '29d2993aacb9'
down_revision = '162fffcec05b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
