"""empty message

Revision ID: 38d7b3f323bf
Revises: 
Create Date: 2022-02-19 07:22:58.399549

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '38d7b3f323bf'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('ads',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('token', sa.String(), nullable=True),
    sa.Column('link', sa.String(), nullable=False),
    sa.Column('chart_link', sa.String(), nullable=True),
    sa.Column('buy_link', sa.String(), nullable=True),
    sa.Column('priority', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('start_at', sa.DateTime(), nullable=True),
    sa.Column('end_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('chat_rooms',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('chat_type', sa.SmallInteger(), nullable=False),
    sa.Column('chat_id', sa.BigInteger(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('token', sa.String(), nullable=True),
    sa.Column('cta_link', sa.String(), nullable=True),
    sa.Column('cta_text', sa.String(), nullable=True),
    sa.Column('dex_link', sa.String(), nullable=True),
    sa.Column('cmc_link', sa.String(), nullable=True),
    sa.Column('cg_link', sa.String(), nullable=True),
    sa.Column('tags', sa.String(), nullable=True),
    sa.Column('logo_url', sa.String(), nullable=True),
    sa.Column('link_count', sa.Integer(), nullable=False),
    sa.Column('scrape_interval', sa.Integer(), nullable=False),
    sa.Column('update_interval', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_chat_rooms_chat_id'), 'chat_rooms', ['chat_id'], unique=False)
    op.create_table('data_sources',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('chat_room_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('ignore', sa.Boolean(), nullable=False),
    sa.Column('data_source_type', sa.String(), nullable=False),
    sa.ForeignKeyConstraint(['chat_room_id'], ['chat_rooms.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_data_sources_data_source_type'), 'data_sources', ['data_source_type'], unique=False)
    op.create_table('link_trackers',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('chat_room_id', sa.Integer(), nullable=False),
    sa.Column('link', sa.String(), nullable=False),
    sa.Column('link_type', sa.String(), nullable=False),
    sa.Column('checked', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['chat_room_id'], ['chat_rooms.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_link_trackers_link_type'), 'link_trackers', ['link_type'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_link_trackers_link_type'), table_name='link_trackers')
    op.drop_table('link_trackers')
    op.drop_index(op.f('ix_data_sources_data_source_type'), table_name='data_sources')
    op.drop_table('data_sources')
    op.drop_index(op.f('ix_chat_rooms_chat_id'), table_name='chat_rooms')
    op.drop_table('chat_rooms')
    op.drop_table('ads')
    # ### end Alembic commands ###
