"""empty message

Revision ID: 3ca10fde0d3c
Revises: c6dd915623ec
Create Date: 2022-02-19 22:08:38.282999

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3ca10fde0d3c'
down_revision = 'c6dd915623ec'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
