"""empty message

Revision ID: 4d1d9cc5f2de
Revises: 9f877f7ff9b2
Create Date: 2022-02-18 15:30:00.410191

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '4d1d9cc5f2de'
down_revision = '9f877f7ff9b2'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('ads', sa.Column('chart_link', sa.String(), nullable=True))
    op.add_column('ads', sa.Column('start_at', sa.DateTime(), nullable=True))
    op.alter_column('ads', 'end_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('ads', 'end_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=False)
    op.drop_column('ads', 'start_at')
    op.drop_column('ads', 'chart_link')
    # ### end Alembic commands ###
