"""empty message

Revision ID: 6db933462259
Revises: d0c8d93d9a23
Create Date: 2022-02-18 15:59:55.318430

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6db933462259'
down_revision = 'd0c8d93d9a23'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('ads', sa.Column('buy_link', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('ads', 'buy_link')
    # ### end Alembic commands ###
