"""empty message

Revision ID: 9083dbc77804
Revises: 9db8cfbc3595
Create Date: 2022-02-17 10:07:28.491135

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9083dbc77804'
down_revision = '9db8cfbc3595'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('chat_rooms_link_trackers')
    op.drop_table('chat_rooms_data_sources')
    op.add_column('data_sources', sa.Column('chat_room_id', sa.Integer(), nullable=False))
    op.create_foreign_key(None, 'data_sources', 'chat_rooms', ['chat_room_id'], ['id'])
    op.add_column('link_trackers', sa.Column('chat_room_id', sa.Integer(), nullable=False))
    op.create_foreign_key(None, 'link_trackers', 'chat_rooms', ['chat_room_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'link_trackers', type_='foreignkey')
    op.drop_column('link_trackers', 'chat_room_id')
    op.drop_constraint(None, 'data_sources', type_='foreignkey')
    op.drop_column('data_sources', 'chat_room_id')
    op.create_table('chat_rooms_data_sources',
    sa.Column('chat_room_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('data_source_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['chat_room_id'], ['chat_rooms.id'], name='chat_rooms_data_sources_chat_room_id_fkey'),
    sa.ForeignKeyConstraint(['data_source_id'], ['data_sources.id'], name='chat_rooms_data_sources_data_source_id_fkey'),
    sa.PrimaryKeyConstraint('chat_room_id', 'data_source_id', name='chat_rooms_data_sources_pkey')
    )
    op.create_table('chat_rooms_link_trackers',
    sa.Column('chat_room_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('link_tracker_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['chat_room_id'], ['chat_rooms.id'], name='chat_rooms_link_trackers_chat_room_id_fkey'),
    sa.ForeignKeyConstraint(['link_tracker_id'], ['link_trackers.id'], name='chat_rooms_link_trackers_link_tracker_id_fkey'),
    sa.PrimaryKeyConstraint('chat_room_id', 'link_tracker_id', name='chat_rooms_link_trackers_pkey')
    )
    # ### end Alembic commands ###
