"""empty message

Revision ID: c6dd915623ec
Revises: dacac1b6b233
Create Date: 2022-02-19 21:23:06.235559

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "c6dd915623ec"
down_revision = "dacac1b6b233"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "chat_room_admins",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("chat_room_id", sa.Integer(), nullable=False),
        sa.Column("user_id", sa.BigInteger(), nullable=False),
        sa.ForeignKeyConstraint(
            ["chat_room_id"],
            ["chat_rooms.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("chat_room_admins")
    # ### end Alembic commands ###
