"""empty message

Revision ID: dacac1b6b233
Revises: 8b3349c27be7
Create Date: 2022-02-19 19:27:56.578899

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "dacac1b6b233"
down_revision = "8b3349c27be7"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "chat_rooms",
        sa.Column("link_age", sa.Integer(), nullable=False, server_default="60"),
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("chat_rooms", "link_age")
    # ### end Alembic commands ###
