"""empty message

Revision ID: de8990d649e1
Revises: def6b96dcf6b
Create Date: 2022-02-17 08:26:35.857258

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'de8990d649e1'
down_revision = 'def6b96dcf6b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
