"""empty message

Revision ID: faacd2de44e4
Revises: 6db933462259
Create Date: 2022-02-18 19:40:30.579970

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'faacd2de44e4'
down_revision = '6db933462259'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('chat_rooms', sa.Column('link_count', sa.Integer(), nullable=False))
    op.add_column('chat_rooms', sa.Column('created_at', sa.DateTime(), nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('chat_rooms', 'created_at')
    op.drop_column('chat_rooms', 'link_count')
    # ### end Alembic commands ###
